[workspace]
# path of the git-cliff configuration
changelog_config = "cliff.toml"
# update dependencies with `cargo update`
dependencies_update = true
# labels for the release PR
pr_labels = ["release"]


